project_name: "ansfab"

# Default HL fabric ports
orderer_port: 7050
api_port: 4000
ca_port: 7054
peer0_port: 7051

# Use couchdb in peers instead of leveldb
#use_couchdb: 'yes'
use_couchdb: 'no'
couchdb_port: 5984

fabric_starter_workdir: "/home/{{ ansible_user }}/{{ project_name }}"

local_artifacts: "/Users/deniskozlov/ocrv-ansfab/artifacts"
docker_artifacts: "{{ fabric_starter_workdir }}/dockercompose"
fabric_artifacts: "{{ fabric_starter_workdir }}/artifacts"

org_dir: "{{ fabric_starter_workdir }}/organizations"
local_org_dir: "{{ local_artifacts }}/organizations"
ca_dir: "{{ org_dir }}/ca"

peer_org: "{{ org_dir }}/peerOrganizations/{{ org }}.{{ global_domain }}"
local_peer_org: "{{ local_org_dir }}/peerOrganizations/{{ org }}.{{ global_domain }}"

orderer_org: "{{ org_dir }}/ordererOrganizations/{{ global_domain }}"
local_orderer_org: "{{ local_org_dir }}/ordererOrganizations/{{ global_domain }}"

peer_dir: "{{ peer_org }}/peers/peer0.{{ org }}.{{ global_domain }}"
local_peer_dir: "{{ local_peer_org }}/peers/peer0.{{ org }}.{{ global_domain }}"
registrar_peer: "{{ peer_org }}"

orderer_dir: "{{ orderer_org }}/orderers/orderer{{ orderer_id | default() }}.{{ global_domain }}"
local_orderer_dir: "{{ local_orderer_org }}/orderers/orderer{{ orderer_id | default() }}.{{ global_domain }}"
registrar_orderer: "{{ orderer_org }}"

admin_dir: "{{ peer_org }}/users/Admin@{{ org }}.{{ global_domain }}"
local_admin_dir: "{{ local_peer_org }}/users/Admin@{{ org }}.{{ global_domain }}"
admin_orderer_dir: "{{ orderer_org }}/users/Admin@{{ global_domain }}"

# Folders to create for configs
fabric_artifacts_folders:
  - "{{ fabric_starter_workdir }}"
  - "{{ docker_artifacts }}"
  - "{{ fabric_artifacts }}"
  - "{{ ca_dir }}"

###### Generate configuration files ######

local_templates:
  - from: "configtxtemplate.yaml"
    to: "{{ local_artifacts }}/configtx.yaml"

ca_templates:
  - from: "fabric-ca-server-config-template.yaml"
    to: "{{ ca_dir }}/fabric-ca-server-{{ org }}.yaml"
  - from: "docker-compose-ca-template.yaml"
    to: "{{ docker_artifacts }}/docker-compose-ca-{{ org }}.yaml"

orderer_templates:
  - from: "configtxtemplate.yaml"
    to: "{{ fabric_artifacts }}/configtx.yaml"
  - from: "docker-compose-orderer-template.yaml"
    to: "{{ docker_artifacts }}/docker-compose-orderer-{{ org }}.yaml"

peer_templates:
  - from: "base.yaml"
    to: "{{ docker_artifacts }}/base.yaml"
  - from: "docker-compose-peer-template.yaml"
    to: "{{ docker_artifacts }}/docker-compose-peer-{{ org }}.yaml"

###### Synchronization artifacts ######

files_to_rsync_peer:
  - from: "{{ peer_org }}/msp"
    to: "{{ local_peer_org }}"
  - from: "{{ peer_dir }}/tls/ca.crt"
    to: "{{ local_peer_dir }}/tls"
  - from: "{{ peer_org }}/tlsca/tlsca.{{ org }}.{{ global_domain }}-cert.pem"
    to: "{{ local_peer_dir }}/msp/tlscacerts"
  - from: "{{ admin_dir }}/msp"
    to: "{{ local_admin_dir }}"

files_to_rsync_root_orderer:
  - from: "{{ orderer_org }}/msp"
    to: "{{ local_orderer_org }}"

files_to_rsync_orderer:
  - from: "{{ orderer_dir }}"
    to: "{{ local_orderer_org }}/orderers"
  - from: "{{ orderer_org }}/tlsca/tlsca.{{ global_domain }}-cert.pem"
    to: "{{ local_orderer_dir }}/tlsca"
  - from: "{{ orderer_dir }}/tls"
    to: "{{ local_orderer_dir }}"