---
- name: Install required packages.
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop: "{{ debian_package_list }}"
  when: ansible_os_family == 'Debian'

- name: Install required packages.
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ redhat_package_list }}"
  when: ansible_os_family == 'RedHat'
