---
all:
  hosts:
    localhost: # localhost connection parameters, used for storing configuration while transferring it between nodes
      ansible_connection: local
  vars:
    global_domain: example.com
    global_chaincode_lang: javascript # Programming language of chaincode
    global_chaincode_version: 1.0 # Your chaincode version
    global_channels:
      - name: common # Channel name
        particapants: # Organizations, should be included in channel
          - org0
          - org1
#          - org2
#          - org3
        chaincode: # Chaincode params
          name: fabcar
          version: "{{ global_chaincode_version }}"
          policy: ""
          init: '{"Args":["init","a","100","b","100"]}'
  children:
    nodes:
      hosts:
        org0.example.com: # Describes which containers will run on this node
          node_roles:
            - root_orderer # This node will be used to generate crypto-config for other orderers
            - orderer
            - peer
            - ca
          org: org0 # Organization name
          orderer_id: 0
          ansible_host: 31.184.253.134 # Real ip address or domain name of the machine
          ansible_user: root  # User with sudo access
          ansible_private_key_file: ~/.ssh/id_rsa # Private key to identify ourselves
          ansible_ssh_port: 22 # Specify ssh-port here, if case of it's not defaulted.
        org1.example.com: # Describes which containers will run on this node
          node_roles:
            - orderer
            - peer
            - ca
          org: org1 # Organization name
          orderer_id: 1
          ansible_host: 80.249.147.91 # Real ip address or domain name of the machine
          ansible_user: root  # User with sudo access
          ansible_private_key_file: ~/.ssh/id_rsa # Private key to identify ourselves
          ansible_ssh_port: 22 # Specify ssh-port here, if case of it's not defaulted.