---
all:
  hosts:
    localhost: # localhost connection parameters, used for storing configuration while transferring it between nodes
      ansible_connection: local
  vars:
    global_domain: example.com
    global_chaincode_lang: golang # Programming language of chaincode
    global_chaincode_version: 1.0 # Your chaincode version
    global_channels:
      - name: common # Channel name
        particapants: # Organizations, should be included in channel
          - org0
#          - org1
#          - org2
#          - org3
        chaincode: # Chaincode params
          name: rails
          version: "{{ global_chaincode_version }}"
          policy: ""
          init: '{"Args":["init","a","100","b","100"]}'
#      - name: bilateral-1 # Channel name
#        particapants: # Organizations, should be included in channel
#          - org2
#          - org3
#        chaincode: # Chaincode params
#          name: relationship
#          version: "{{ global_chaincode_version }}"
#          policy: ""
#          init: '{"Args":["init","a","100","b","100"]}'
    orderer_count: 1 # Amount of orderers in network
  children:
    nodes:
      hosts:
        org0.example.com: # Describes which containers will run on this node
          node_roles:
            - root_orderer # This node will be used to generate crypto-config for other orderers
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - root_peer # This node will be used to create channels and instantiate chaincode
            - explorer # This node will serve hyperledger fabric explorer
            - ca
          org: org0 # Organization name
          orderer_id: 0
          ansible_host: 31.184.253.134 # Real ip address or domain name of the machine
          ansible_user: root  # User with sudo access
          ansible_private_key_file: ~/.ssh/id_rsa # Private key to identify ourselves
          ansible_ssh_port: 22 # Specify ssh-port here, if case of it's not defaulted.
        org1.example.com: # Describes which containers will run on this node
          node_roles:
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - root_peer # This node will be used to create channels and instantiate chaincode
            - explorer # This node will serve hyperledger fabric explorer
            - ca
          org: org1 # Organization name
          orderer_id: 1
          ansible_host: 80.249.147.91 # Real ip address or domain name of the machine
          ansible_user: root  # User with sudo access
          ansible_private_key_file: ~/.ssh/id_rsa # Private key to identify ourselves
          ansible_ssh_port: 22 # Specify ssh-port here, if case of it's not defaulted.
        # Same structure for any other nodes
#        org1.example.com:
#          node_roles:
#            - orderer # This node will host an orderer-service
#            - peer # This node will host peers and api containers for organization
#            - explorer
#          org: org1
#          orderer_id: 1 # ID of orderer-service which is running on this host
#          ansible_host: 54.211.182.66
#          ansible_user: ubuntu
#          #ansible_private_key_file: ~/path-to-private-key
#          ansible_ssh_port: 22
#        org2.example.com:
#          node_roles:
#            - orderer
#            - peer
#            - explorer
#          org: org2
#          orderer_id: 2
#          ansible_host: 3.81.75.88
#          ansible_user: ubuntu
#          #ansible_private_key_file: ~/path-to-private-key
#          ansible_ssh_port: 22
#        org3.example.com: # This node will host only kafka-broker and peer.
#          node_roles:
#            - peer
#            - orderer
#            - explorer
#          org: org3
#          orderer_id: 3
#          ansible_host: 23.20.192.198
#          ansible_user: ubuntu
#          #ansible_private_key_file: ~/path-to-private-key
#          ansible_ssh_port: 22
