---
- hosts: nodes
  become: true

  roles:
    - start-orderer-containers
    - start-peer-containers
    - create-channels
    - install-chaincode

#---
#- hosts: nodes
##  connection: local
#  tasks:
#
#    - name: Changing ownership of project
#      raw: "sudo chown -R root {{ fabric_starter_workdir }}"
#
#    - name: Starting orderer
#      block:
#
#        - name: Start orderer
#          raw: "docker-compose -f {{ docker_artifacts }}/docker-compose-orderer-{{ org }}.yaml up -d 2>&1"
#
#    - name: Starting peers
#      block:
#
#        - name: Start docker containers
#          raw: "docker-compose -f {{ docker_artifacts }}/docker-compose-peer-{{ org }}.yaml up -d 2>&1"
#
#    - name: Create channels
#      include_tasks: create-channels.yaml
#
#    - name: Install chaincode
#      include_tasks: install-chaincode.yaml
#      loop: "{{ global_channels }}"

