---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - npm
    - python3-pip
  when: ansible_os_family == 'Debian'

- name: Install common packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - npm
    - python-pip
    - python-setuptools
    - openssh-askpass
  when: ansible_os_family == 'RedHat'

- name: Upgrade pip
  shell: "python -m pip install --upgrade pip"

- pip:
    name: "{{ item }}"
    state: latest
  loop:
    - docker
    - docker-compose