---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - npm
    - python3-pip
    - python-setuptools
    - ssh-askpass
  when: ansible_os_family == 'Debian'

- name: Install common packages
  shell: "curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -"
  when: ansible_os_family == 'RedHat'

- name: Install common packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - nodejs
    - python3
    - python-setuptools
    - openssh-askpass
  when: ansible_os_family == 'RedHat'

- name: Install docker, docker-compose via pip3
  shell: "pip3 install docker docker-compose"
