---
- name: Install fabric-tools
  raw: "rm -rf $HOME/fabric-tools &&
        mkdir $HOME/fabric-tools &&
        cd $HOME/fabric-tools &&
        curl -sSL https://bit.ly/2ysbOFE | bash -s &&
        cd fabric-samples &&
        sudo cp bin/* /usr/bin"
  ignore_errors: true