chaincode_lang: node # Programming language of chaincode
chaincode_version: 1.0 # Your chaincode version
channels:
  - name: rails # Channel name
    particapants: # Organizations, should be included in channel
      - rzd
      - hmk
      - rspm
    chaincode: # Chaincode params
      name: rails
      version: "{{ chaincode_version }}"
      policy: ""
      init: '{"Args":["init","a","100","b","100"]}'