---
fabric_starter_workdir: "/home/{{ ansible_user }}/{{ project_name }}"

fabric_artifacts: "{{ fabric_starter_workdir }}/crypto-config"
local_artifacts: "./artifacts"

peer_org: "{{ fabric_artifacts }}/peerOrganizations/{{ org }}.{{ domain }}"
orderer_org: "{{ fabric_artifacts }}/ordererOrganizations/{{ domain }}"

peer_dir: "{{ peer_org }}/peers/peer0.{{ org }}.{{ domain }}"
admin_dir: "{{ peer_org }}/users/Admin@{{ org }}.{{ domain }}"

local_orderer_org: "{{ local_artifacts }}/ordererOrganizations/{{ domain }}"
local_peer_org: "{{ local_artifacts }}/peerOrganizations/{{ org }}.{{ domain }}"

local_orderer_dir: "{{ local_orderer_org }}/orderers/orderer{{ orderer_id | default() }}.{{ domain }}"
local_peer_dir: "{{ local_peer_org }}/peers/peer0.{{ org }}.{{ domain }}"

local_admin_dir: "{{ local_peer_org }}/users/Admin@{{ org }}.{{ domain }}"