---
- name: Transfer Orderer configuration files
  template:
    src: "{{ item.from }}"
    dest: "{{ item.to }}"
  loop: "{{ orderer_templates }}"

- name: Tear down existing Orderer container
  docker_compose:
    project_src: "{{ docker_artifacts }}"
    files:
      - "docker-compose-orderer-{{ org }}.yaml"
    remove_volumes: yes
    #remove_orphans: yes
    state: absent
  vars:
    ansible_python_interpreter: /bin/python3

- name: Start Orderer container
  docker_compose:
    project_src: "{{ docker_artifacts }}"
    files:
      - "docker-compose-orderer-{{ org }}.yaml"
    state: present
  vars:
    ansible_python_interpreter: /bin/python3